### ISSUE TITLE
Getting a 401 when I try to sync with Jira

### ISSUE THREAD

**Issue by mtuckerb** [BoxThatBeat/obsidian-agile-task-notes#17]
I am getting a 401 error when I try to sync  with Jira. Wondering if something changed on their API recently. I can look into this myself, but wanted to pin it here in case others are having the same problem.

**Comment by BoxThatBeat** [comment]
Weird, I just tried and it worked for me. I assume you had it working prior to today?

**Comment by mtuckerb** [comment]
Yes, I think my first failure was a week ago. I'll poke around a little on my end and report back

**Comment by mtuckerb** [comment]
i just ran the two REST requests that the plugin makes, with the same arguments from an API client on the same machine that is failing and they came back with valid responses. I double checked my inputs in the plugin as well.  I even removed the plugin completely and started from scratch. Still getting a 401. Can you think of something I can test. I'm happy to run a debugger, but I'm not sure how to do that in this context.

**Comment by BoxThatBeat** [comment]
I knew my lazy try-catch solution was gonna bite me eventually haha. Ideally I should put all requests that might throw an error into separate try-catches so I can log with which request the code fails to help with debugging. Maybe that should be added to the backlog. For now, unfortunately I have not yet found a good way to debug plugins for Obsidian since it is compiled from JS to TS before being used by Obsidian. However, you can add the line `debugger` in the code and then recompile to basically have a jank breakpoint. So in this case maybe put one before each request and see what it makes it to, and put one in the catch statement. That's all I can think of with this info, let me know what you find out!

**Comment by BoxThatBeat** [comment]
Ohh, I forgot I had added another person's additional feature to the newest version (new auth mode). That is probably what this is. Do you have this setting set to `Basic Auth`? 
![image](https://user-images.githubusercontent.com/28713093/222562609-f13da904-c172-4186-bced-d8d5445def21.png)

**Comment by mtuckerb** [comment]
💥 That was it. I had Personal Access Token. Problem Solved!

**Comment by BoxThatBeat** [comment]
Great! Glad it was that, sorry for the inconvenience. Was it Personal Access Token by default? It shouldn't be haha

**Comment by BoxThatBeat** [comment]
I'll leave this issue open in case others have the same issue.

**Comment by mtuckerb** [comment]
i think i switched it to that, but now I don't remember when i would have.
